server:
  port: 8000

spring:
  application.name: api-gateway-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # profiles.include: api-gateway-route-and-filters
  # config.import: classpath:api-gateway-route-and-filters.yml
  devtools:
    livereload.enabled: true
    restart.enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management.endpoints.web.exposure.include: refresh, health, beans, httpexchanges, busrefresh

debug-constant-a: a