spring:
  profiles.include: 
    - route-user-service
    - route-etc
  cloud.gateway.default-filters:
    - name: GlobalFilter
      args:
        baseMessage: "Spring Cloud Gateway GlobalFilter"
        preLogger: true
        postLogger: true
